name: rps-cv
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - scikit-learn>=0.20
  - pandas>=0.24
  - jupyter
  - nodejs
  - matplotlib>=3.0
  - opencv>=3.3
  - scikit-image>=0.13
  - scikit-optimize>0.5
  - pip:
    - git+https://github.com/DrGFreeman/rps-cv
